// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbFWSuEiAGd2xHnxf6_KEh3hU_QiSHldY',
    appId: '1:382067507824:web:d76d9cf02d5c20296d2ab5',
    messagingSenderId: '382067507824',
    projectId: 'reddit-clone-c5c25',
    authDomain: 'reddit-clone-c5c25.firebaseapp.com',
    storageBucket: 'reddit-clone-c5c25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOw5vYDlrm93imaSrQqoSOoc0uDq5jSL0',
    appId: '1:382067507824:android:35a1485eb08051896d2ab5',
    messagingSenderId: '382067507824',
    projectId: 'reddit-clone-c5c25',
    storageBucket: 'reddit-clone-c5c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSr1CM5IY0RDyZugeU_tFgpVCYLwzB3RI',
    appId: '1:382067507824:ios:778935de6cdb66ec6d2ab5',
    messagingSenderId: '382067507824',
    projectId: 'reddit-clone-c5c25',
    storageBucket: 'reddit-clone-c5c25.appspot.com',
    androidClientId: '382067507824-nvjh73n2r84bnfgvjkse0osrlnkrk9nv.apps.googleusercontent.com',
    iosClientId: '382067507824-gbtdpkfpdmv4kccpmcd6fl8umfpujlch.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbFWSuEiAGd2xHnxf6_KEh3hU_QiSHldY',
    appId: '1:382067507824:web:22e927fa086f6da06d2ab5',
    messagingSenderId: '382067507824',
    projectId: 'reddit-clone-c5c25',
    authDomain: 'reddit-clone-c5c25.firebaseapp.com',
    storageBucket: 'reddit-clone-c5c25.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAbFWSuEiAGd2xHnxf6_KEh3hU_QiSHldY',
    appId: '1:382067507824:web:0e09ed71d3565f7b6d2ab5',
    messagingSenderId: '382067507824',
    projectId: 'reddit-clone-c5c25',
    authDomain: 'reddit-clone-c5c25.firebaseapp.com',
    storageBucket: 'reddit-clone-c5c25.appspot.com',
  );
}
