// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASPMm6eQDETskZ2YC8oBRMG9_Tg2xjRRs',
    appId: '1:865861095253:web:7fc441b8315b70c5b2a9dc',
    messagingSenderId: '865861095253',
    projectId: 'dima-app-372615',
    authDomain: 'dima-app-372615.firebaseapp.com',
    storageBucket: 'dima-app-372615.appspot.com',
    measurementId: 'G-ZPX7D60K5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH68XT2ggH1OEdE24B97HhNvciHAcYspA',
    appId: '1:865861095253:android:14df6072112af0c0b2a9dc',
    messagingSenderId: '865861095253',
    projectId: 'dima-app-372615',
    storageBucket: 'dima-app-372615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfYsc1D0I2c5xDna7FNCq6uc0OmMcXZcs',
    appId: '1:865861095253:ios:a1091aaa945ba3fab2a9dc',
    messagingSenderId: '865861095253',
    projectId: 'dima-app-372615',
    storageBucket: 'dima-app-372615.appspot.com',
    iosClientId: '865861095253-6thom5kkav2utjilf04qsdia3aup0nv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dimaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfYsc1D0I2c5xDna7FNCq6uc0OmMcXZcs',
    appId: '1:865861095253:ios:a1091aaa945ba3fab2a9dc',
    messagingSenderId: '865861095253',
    projectId: 'dima-app-372615',
    storageBucket: 'dima-app-372615.appspot.com',
    iosClientId: '865861095253-6thom5kkav2utjilf04qsdia3aup0nv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dimaApp',
  );
}
